name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-forbidden-words:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: juspay/hyperswitch-sdk-utils
          ref: main
          path: shared-code

      - name: Scan for forbidden words
        run: |
          forbidden_words=("Console.log" "mutable" "%identity")
          excluded_files=("prepareS3.js" "server.js" "src/utility/logics/Window.res")
          find . -type f \( ! -path "*/.git/*" ! -path "*/node_modules/*" ! -path "*/build/*" ! -path "*/dist/*" ! -path "*/.github/*" ! -path "*/.yarn/*" \) | grep -v -E "$(IFS='|'; echo "${excluded_files[*]}")" | while read -r file; do
            for word in "${forbidden_words[@]}"; do
              if grep -Hn "$word" "$file"; then
                echo "❌ Forbidden word '$word' found in $file!"
                exit 1
              fi
            done
          done

  compile-rescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: juspay/hyperswitch-sdk-utils
          ref: main
          path: shared-code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Compile ReScript and fail on warnings
        run: |
          if npm run re:check; then
            echo "✅ ReScript compilation successful!"
          else
            echo "❌ ReScript compilation failed with warnings!"
            exit 1
          fi
